version: "3.9"
services:
  ide:
    build:
      context: ../
      dockerfile: container/Containerfile.ide
    image: torizonextras/ide

  pwsh-gitlab:
    build:
      context: ../
      dockerfile: container/Containerfile.gitlab
    image: torizonextras/pwsh-gitlab
