name: Rust Debug Containers
on:
  push:
    branches:
      - dev
      - bookworm

jobs:
  rust-debug:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/bookworm' || github.ref == 'refs/heads/dev'
    name: Rust Container Debug
    strategy:
      matrix:
        project:
          - folder: rustSlint
            container: rust-slint
            vendor: "{ arch: 'arm64', torizon_arch: 'aarch64' }"

    steps:
      - uses: actions/checkout@v3

      - name: Get Host Absolute Workspace Path
        run: |
          echo "${{ github.workspace }}" >> abs-path
          cat abs-path

      - name: Build ${{ matrix.project.folder }} Dockerfile
        shell: pwsh
        env:
          PROJECT_FOLDER: ${{ matrix.project.folder }}
          PROJECT_CONTAINER: ${{ matrix.project.container }}
          VENDOR: ${{ matrix.project.vendor }}
          DOCKER_LOGIN: localhost:5002

        run: |
          $_vendor = ($env:VENDOR | ConvertFrom-Json)
          $env:TORIZON_ARCH = $_vendor.torizon_arch
          $env:PROJECT_ARCH = $_vendor.arch

          scripts/createFromTemplate.ps1 `
            $env:GITHUB_WORKSPACE/$env:PROJECT_FOLDER `
            "${env:PROJECT_FOLDER}CITest" `
            "${env:PROJECT_CONTAINER}-ci-test" `
            $env:GITHUB_WORKSPACE `
            $env:PROJECT_FOLDER `
            false `
            false

          cp abs-path "${env:GITHUB_WORKSPACE}/${env:PROJECT_FOLDER}CITest"
          cd "${env:GITHUB_WORKSPACE}/${env:PROJECT_FOLDER}CITest"


          $_settingsJson = Get-Content -Path ".vscode/settings.json" | ConvertFrom-Json
          $_settingsJson.torizon_arch = $env:TORIZON_ARCH
          Set-Content -Path ".vscode/settings.json" -Value ($_settingsJson | ConvertTo-Json) -Encoding UTF8

          # TODO: this is bad, but it's the only way to make it work for now
          chmod 777 . -R

          ./.vscode/tasks.ps1 run run-torizon-binfmt
          ./.vscode/tasks.ps1 run build-debug-${env:PROJECT_ARCH}
          ./.vscode/tasks.ps1 run copy-debug-executable-${env:PROJECT_ARCH}
          ./.vscode/tasks.ps1 run build-container-torizon-debug-${env:PROJECT_ARCH}
